name: mpx-nlp
channels:
    - default
    - anaconda
    - conda-forge
dependencies:

    - python=3.8
    # This is what the desired medspacy needs at the moment
    - spacy>=3.1,<3.2
    - spacy-model-en_core_web_sm
    - nb_conda
    - pandas
    - numpy
    - scipy
    - scikit-learn
    - pytest
    - pip
    - pip:
      - medspacy==0.2.0.0
 
